# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/tests/testall
# Target is an application:  

include( ../../../global.pro )

TARGETDEPS += ../../../src/processors/toolkit/libtoolkit.so \
              ../../../src/geddei/libgeddei.so \
              ../../../src/qtextra/libqtextra.so
LIBS += -ltoolkit \
        -lgeddei \
	-lqtextra
INCLUDEPATH = ../../../src/processors/toolkit \
              ../../../src/geddei \
              ../../../src/qtextra 
QMAKE_LIBDIR = ../../../src/processors/toolkit \
               ../../../src/geddei \
              ../../../src/qtextra 
TEMPLATE = app 
SOURCES += testfileout.cpp 
