# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/tests
# Target is a subdirs project 

include( ../../global.pro )

SUBDIRS += testbuffer \
           testspeed \
           testflow \
           testsplit \
           testfileout \
           testmulti \
           testdemux \
           testall \
           testproperties

gat:SUBDIRS += testgat

TEMPLATE = subdirs
