# File generated by kdevelop's qmake manager.
# -------------------------------------------
# Subdir relative project main directory: ./src/remote/tests/testnodeclient
# Target is an application:

include( ../../../../global.pro )

TARGETDEPS += ../../../../src/remote/rgeddei/librgeddei.so \
              ../../../../src/qtextra/libqtextra.so \
              ../../../../src/geddei/libgeddei.so
LIBS += -lrgeddei \
        -lqtextra \
        -lgeddei
INCLUDEPATH += ../../../../src/remote/rgeddei \
               ../../../../src/geddei \
               ../../../../src/qtextra
QMAKE_LIBDIR = ../../../../src/remote/rgeddei \
               ../../../../src/qtextra \
               ../../../../src/geddei
TEMPLATE = app
SOURCES += testnodeclient.cpp
