# File generated by kdevelop's qmake manager.
# -------------------------------------------
# Subdir relative project main directory: ./src/processors
# Target is a subdirs project

SUBDIRS += mir \
		   toolkit \
		   example \
		   math \
		   viewers \
		   aubio
TEMPLATE = subdirs
