# File generated by kdevelop's qmake manager.
# -------------------------------------------
# Subdir relative project main directory: ./src/remote/tests/testspeed
# Target is an application:

include( ../../../../global.pro )

TARGETDEPS += ../../../../src/processors/toolkit/libtoolkit.so \
              ../../../../src/remote/rgeddei/librgeddei.so \
              ../../../../src/qtextra/libqtextra.so \
              ../../../../src/geddei/libgeddei.so
LIBS += -lrgeddei \
        -lgeddei \
        -lqtextra \
        -ltoolkit
INCLUDEPATH += ../../../../src/remote/rgeddei \
               ../../../../src/processors/toolkit \
               ../../../../src/geddei \
               ../../../../src/qtextra
QMAKE_LIBDIR = ../../../../src/remote/rgeddei \
               ../../../../src/geddei \
               ../../../../src/qtextra \
               ../../../../src/processors/toolkit
TEMPLATE = app

SOURCES += testspeed.cpp
