# File generated by kdevelop's qmake manager.
# -------------------------------------------
# Subdir relative project main directory: ./src/remote/tests
# Target is a subdirs project

TEMPLATE = subdirs
SUBDIRS += testnodeclient \
           testrdemux \
           testspeed
