# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/examples
# Target is a subdirs project 

SUBDIRS += incremental 
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
