# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is a subdirs project 

SUBDIRS += qtextra \
           geddei \
           processors \
           tests \
           remote \
           exinfo \
           nite \
           examples 
TEMPLATE = subdirs
