# File generated by kdevelop's qmake manager.
# -------------------------------------------
# Subdir relative project main directory: ./src/remote
# Target is a subdirs project

include( ../../global.pro )

TEMPLATE = subdirs
SUBDIRS += rgeddei \
           nodeserver \
           tests

