# File generated by kdevelop's qmake manager.
# -------------------------------------------
# Subdir relative project main directory: ./src/nite
# Target is an application:

include(../../exscalibar.pri)

INSTALLS += target
target.path = $$PREFIX/bin
TARGETDEPS += $$DESTDIR/libqtextra.so \
              $$DESTDIR/libgeddei.so 
LIBS +=	-lqtextra \
	-lgeddei
INCLUDEPATH += ../../src/geddei \
               ../../src/qtextra
TEMPLATE = app
SOURCES += exinfo.cpp
